# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 251e2cec2f7c13505dcfb46a8189eb09631f969fa4c9830dc6612193e47753d886c827faed7d93c38d2222b4aeeddff63fade7fbc0611a9dfaed12e5fd40419d

test:
  secret_key_base: a61e46cfb08bd87038f64beb3bfd969758736405f348f00bf4493c7e51d3db43a3636aece7c27e164320b478e677266e3038d4e8058ae5b2d215c129bb6ffe13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
